export type BlogPost = {
  id: string
  title: string
  excerpt: string
  content: string
  author: string
  date: string
  readTime: string
  category: string
  image?: string
  featured?: boolean
  premium?: boolean
}

export const blogPosts: BlogPost[] = [
  {
    id: 'cach-lap-ke-hoach-tai-chinh-hieu-qua',
    title: '7 Bước Lập Kế Hoạch Tài Chính Hiệu Quả Cho Người Trẻ',
    excerpt:
      'Khám phá cách xây dựng kế hoạch tài chính vững chắc từ tuổi 20, giúp bạn đạt được tự do tài chính sớm hơn.',
    content:
      `Lập kế hoạch tài chính là một trong những kỹ năng quan trọng nhất mà mọi người trẻ cần học. Trong bài viết này, chúng ta sẽ khám phá 7 bước cơ bản để xây dựng một kế hoạch tài chính hiệu quả.\n\n## 1. Đánh giá tình hình tài chính hiện tại\n\nTrước khi lập kế hoạch, bạn cần hiểu rõ tình hình tài chính hiện tại của mình:\n- Thu nhập hàng tháng\n- Chi phí cố định và biến đổi\n- Tài sản hiện có\n- Các khoản nợ (nếu có)\n\n## 2. Xác định mục tiêu tài chính\n\nMục tiêu tài chính cần được chia thành:\n- **Ngắn hạn** (1-2 năm): Mua laptop, du lịch\n- **Trung hạn** (3-5 năm): Mua xe, kết hôn\n- **Dài hạn** (10+ năm): Mua nhà, nghỉ hưu\n\n## 3. Tạo ngân sách chi tiêu\n\nÁp dụng quy tắc 50/30/20:\n- 50% cho nhu cầu thiết yếu\n- 30% cho giải trí và sở thích\n- 20% cho tiết kiệm và đầu tư\n\n## 4. Xây dựng quỹ dự phòng\n\nQuỹ dự phòng nên bằng 3-6 tháng chi phí sinh hoạt, giúp bạn ứng phó với các tình huống bất ngờ.\n\n## 5. Bắt đầu đầu tư sớm\n\nThời gian là yếu tố quan trọng nhất trong đầu tư. Bắt đầu đầu tư sớm, dù chỉ với số tiền nhỏ, sẽ mang lại lợi ích lớn nhờ lãi kép.\n\n## 6. Quản lý rủi ro\n\nMua bảo hiểm để bảo vệ tài sản và thu nhập của bạn khỏi các rủi ro không lường trước được.\n\n## 7. Đánh giá và điều chỉnh định kỳ\n\nHàng quý, hãy đánh giá lại kế hoạch tài chính và điều chỉnh cho phù hợp với tình hình thực tế.\n\n---\n\n*Với PlanAI, bạn có thể tạo ra kế hoạch tài chính cá nhân hóa chỉ trong vài phút. Hãy thử ngay hôm nay!*`,
    author: 'PlanAI Team',
    date: '2024-01-15',
    readTime: '8 phút đọc',
    category: 'Tài chính cá nhân',
    image: '/blog/cover-default.svg',
    featured: true,
  },
  // Premium posts (metadata only; content served via gated API)
  {
    id: 'premium-tu-do-tai-chinh-truoc-35',
    title: 'Lộ Trình Tự Do Tài Chính Trước 35: Tư Duy, Danh Mục, Dòng Tiền',
    excerpt: 'Khung tư duy và hệ thống thực thi giúp rút ngắn thời gian đạt tự do tài chính.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Research',
    date: '2024-07-01',
    readTime: '25 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-100tr-dau-tien-tu-kinh-doanh-so',
    title: '100 Triệu Đầu Tiên Từ Kinh Doanh Số: Sản Phẩm, Kênh, Phễu',
    excerpt: 'Xây phễu sản phẩm số lợi nhuận cao với lộ trình 90-180 ngày.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Academy',
    date: '2024-07-02',
    readTime: '28 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-he-thong-thu-nhap-phu-20tr-thang',
    title: 'Hệ Thống Thu Nhập Phụ 20 Triệu/Tháng Cho Người Bận Rộn',
    excerpt: 'Blueprint thực thi theo tuần cho 3 nguồn thu phụ bền vững.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Team',
    date: '2024-07-03',
    readTime: '26 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-quy-hoach-tai-san-ca-nhan',
    title: 'Quy Hoạch Tài Sản Cá Nhân: Cấu Trúc Tối Ưu Thuế, Rủi Ro, Tính Thanh Khoản',
    excerpt: 'Thiết kế cấu trúc tài sản cá nhân an toàn và hiệu quả.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Research',
    date: '2024-07-04',
    readTime: '30 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-psychology-tien-bac',
    title: 'Tâm Lý Học Tiền Bạc: 12 Cơ Chế Ảnh Hưởng Quyết Định Tài Chính',
    excerpt: 'Hiểu tâm lý để ra quyết định tài chính tốt hơn và bền vững.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Research',
    date: '2024-07-05',
    readTime: '24 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-portfolio-da-tai-san',
    title: 'Danh Mục Đa Tài Sản: Cân Bằng Tăng Trưởng Và An Toàn',
    excerpt: 'Khung phân bổ cổ phiếu, trái phiếu, vàng, bất động sản, tiền mặt.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Research',
    date: '2024-07-06',
    readTime: '27 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-ngay-nghiem-tuc-voi-tuong-lai-tai-chinh',
    title: 'Ngày Bạn Nghiêm Túc Với Tương Lai Tài Chính: Checklist 30 Ngày',
    excerpt: 'Checklist 30 ngày để thiết lập hệ thống tài chính cá nhân.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Team',
    date: '2024-07-07',
    readTime: '22 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-sai-lam-dau-tu-dat-gia',
    title: '10 Sai Lầm Đầu Tư Đắt Giá Và Cách Tránh',
    excerpt: 'Những bẫy tâm lý và kỹ thuật khiến bạn mất tiền không đáng.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Research',
    date: '2024-07-08',
    readTime: '23 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-chi-tieu-thong-minh-o-tp-lon',
    title: 'Chi Tiêu Thông Minh Ở Thành Phố Lớn: Sống Tốt, Tối Ưu Chi Phí',
    excerpt: 'Mô hình chi tiêu và tối ưu hoá theo bối cảnh người trẻ.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Team',
    date: '2024-07-09',
    readTime: '20 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-thuong-luong-luong-thuong',
    title: 'Thương Lượng Lương Thưởng: Từ Chuẩn Bị Đến Ký Hợp Đồng',
    excerpt: 'Khung đàm phán dựa trên dữ liệu và giá trị tạo ra.',
    content: 'Premium content. Use API to fetch.',
    author: 'HR Insider',
    date: '2024-07-10',
    readTime: '21 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-xay-dung-thuong-hieu-ca-nhan',
    title: 'Xây Dựng Thương Hiệu Cá Nhân Để Tăng Thu Nhập',
    excerpt: 'Chiến lược nội dung, hệ sinh thái kênh, và chuyển đổi doanh thu.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Academy',
    date: '2024-07-11',
    readTime: '26 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-phong-ngua-rui-ro-he-thong',
    title: 'Phòng Ngừa Rủi Ro Hệ Thống Cho Tài Chính Cá Nhân',
    excerpt: 'Kịch bản xấu và cách bảo vệ dòng tiền, tài sản.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Research',
    date: '2024-07-12',
    readTime: '24 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-lai-kep-cuoc-song',
    title: 'Lãi Kép Trong Cuộc Sống: Tiền Bạc, Kỹ Năng, Quan Hệ',
    excerpt: 'Áp dụng tư duy lãi kép để tăng tốc mọi mặt tài chính.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Team',
    date: '2024-07-13',
    readTime: '22 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-he-sinh-thai-kiem-tien-online',
    title: 'Hệ Sinh Thái Kiếm Tiền Online: Từ Kênh, Nội Dung Đến Sản Phẩm',
    excerpt: 'Thiết kế hệ sinh thái tạo thu nhập bền vững qua nhiều kênh.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Academy',
    date: '2024-07-14',
    readTime: '25 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'premium-nghi-huu-som-tai-viet-nam',
    title: 'Nghỉ Hưu Sớm Thực Tế Tại Việt Nam: Lộ Trình Và Con Số',
    excerpt: 'Cách triển khai FIRE thực tế với thu nhập trung bình.',
    content: 'Premium content. Use API to fetch.',
    author: 'PlanAI Research',
    date: '2024-07-15',
    readTime: '28 phút đọc',
    category: 'Bài viết trả phí',
    premium: true,
  },
  {
    id: 'ai-thay-doi-quy-trinh-lap-ke-hoach',
    title: 'AI Đang Thay Đổi Cách Chúng Ta Lập Kế Hoạch Tài Chính',
    excerpt:
      'Tìm hiểu cách trí tuệ nhân tạo giúp tối ưu hóa quy trình lập kế hoạch tài chính và đưa ra những lời khuyên cá nhân hóa.',
    content:
      `Trí tuệ nhân tạo (AI) đang cách mạng hóa nhiều lĩnh vực, và lập kế hoạch tài chính không phải là ngoại lệ. Hãy cùng khám phá cách AI đang thay đổi cách chúng ta tiếp cận tài chính cá nhân.\n\n## AI trong Lập Kế Hoạch Tài Chính\n\nAI có thể phân tích hàng ngàn dữ liệu trong vài giây, từ đó đưa ra những khuyến nghị chính xác và cá nhân hóa cho từng người dùng.\n\n### Lợi ích của AI:\n\n1. **Phân tích dữ liệu nhanh chóng**: AI có thể xử lý và phân tích lượng lớn dữ liệu tài chính\n2. **Cá nhân hóa cao**: Mỗi kế hoạch được tạo ra phù hợp với hoàn cảnh cụ thể\n3. **Dự đoán xu hướng**: AI có thể dự báo các xu hướng thị trường\n4. **Tối ưu hóa chi phí**: Giảm thời gian và chi phí tư vấn tài chính\n\n## Tương Lai của AI trong Tài Chính\n\nTrong tương lai, AI sẽ trở nên thông minh hơn, có thể:\n- Tự động điều chỉnh kế hoạch theo thay đổi của thị trường\n- Đưa ra cảnh báo sớm về rủi ro tài chính\n- Tích hợp với các ứng dụng ngân hàng và đầu tư\n\n---\n\n*PlanAI sử dụng công nghệ AI tiên tiến để tạo ra những kế hoạch tài chính thông minh và hiệu quả.*`,
    author: 'Nguyễn Minh Anh',
    date: '2024-01-10',
    readTime: '6 phút đọc',
    category: 'Công nghệ',
    image: '/blog/cover-default.svg',
    featured: false,
  },
  {
    id: 'dau-tu-cho-nguoi-moi-bat-dau',
    title: 'Hướng Dẫn Đầu Tư Cho Người Mới Bắt Đầu',
    excerpt:
      'Những kiến thức cơ bản về đầu tư mà mọi người trẻ cần biết để bắt đầu hành trình xây dựng tài sản.',
    content:
      `Đầu tư là một phần quan trọng trong kế hoạch tài chính, nhưng nhiều người trẻ vẫn còn e ngại bước vào thế giới này. Bài viết này sẽ cung cấp những kiến thức cơ bản để bạn có thể bắt đầu đầu tư một cách tự tin.\n\n## Tại Sao Cần Đầu Tư?\n\nLạm phát làm giảm giá trị đồng tiền theo thời gian. Nếu chỉ gửi tiết kiệm, tài sản của bạn sẽ mất giá. Đầu tư giúp:\n- Chống lạm phát\n- Tăng trưởng tài sản\n- Đạt được tự do tài chính\n\n## Các Kênh Đầu Tư Phổ Biến\n\n### 1. Chứng khoán\n- **Ưu điểm**: Thanh khoản cao, tiềm năng lợi nhuận lớn\n- **Nhược điểm**: Rủi ro cao, cần kiến thức chuyên môn\n\n### 2. Trái phiếu\n- **Ưu điểm**: Ổn định, rủi ro thấp\n- **Nhược điểm**: Lợi nhuận thấp hơn cổ phiếu\n\n### 3. Quỹ đầu tư\n- **Ưu điểm**: Đa dạng hóa, quản lý chuyên nghiệp\n- **Nhược điểm**: Phí quản lý\n\n### 4. Bất động sản\n- **Ưu điểm**: Tài sản hữu hình, chống lạm phát tốt\n- **Nhược điểm**: Cần vốn lớn, thanh khoản thấp\n\n## Nguyên Tắc Đầu Tư Cơ Bản\n\n1. **Đa dạng hóa**: Không đặt tất cả trứng vào một giỏ\n2. **Đầu tư dài hạn**: Thời gian là bạn của nhà đầu tư\n3. **Học hỏi liên tục**: Thị trường luôn thay đổi\n4. **Kiểm soát cảm xúc**: Không để sợ hãi hay tham lam chi phối\n\n## Bắt Đầu Như Thế Nào?\n\n1. Học kiến thức cơ bản\n2. Xác định mục tiêu đầu tư\n3. Đánh giá khả năng chấp nhận rủi ro\n4. Bắt đầu với số tiền nhỏ\n5. Tăng dần khi có kinh nghiệm\n\n---\n\n*Sử dụng PlanAI để tạo ra chiến lược đầu tư phù hợp với mục tiêu và khả năng tài chính của bạn.*`,
    author: 'Trần Văn Hùng',
    date: '2024-01-05',
    readTime: '10 phút đọc',
    category: 'Đầu tư',
    image: '/blog/cover-default.svg',
    featured: false,
  },
  {
    id: 'kiem-tien-online-hieu-qua',
    title: '10 Cách Kiếm Tiền Online Hiệu Quả',
    excerpt:
      'Khám phá những cách kiếm tiền online phổ biến và hiệu quả, phù hợp với mọi kỹ năng và sở thích.',
    content:
      `Internet đã mở ra vô số cơ hội kiếm tiền online. Dưới đây là 10 cách kiếm tiền online hiệu quả mà bạn có thể bắt đầu ngay hôm nay.\n\n## 1. Freelancing\n\nCung cấp dịch vụ theo dự án trong các lĩnh vực:\n- Thiết kế đồ họa\n- Viết content\n- Lập trình\n- Dịch thuật\n- Marketing\n\n**Thu nhập**: 500k - 50 triệu/tháng tùy kỹ năng\n\n## 2. Affiliate Marketing\n\nQuảng bá sản phẩm của người khác và nhận hoa hồng:\n- Tạo content review sản phẩm\n- Chia sẻ link affiliate trên social media\n- Xây dựng website niche\n\n**Thu nhập**: 1-20 triệu/tháng\n\n...`,
    author: 'Lê Thị Mai',
    date: '2024-01-01',
    readTime: '12 phút đọc',
    category: 'Kiếm tiền online',
    image: '/blog/cover-default.svg',
    featured: false,
  },
  {
    id: 'tang-thu-nhap-cho-dan-van-phong',
    title: 'Lộ Trình Tăng Thu Nhập Cho Dân Văn Phòng Trong 12 Tháng',
    excerpt:
      'Kế hoạch từng bước giúp bạn tăng thu nhập 20-50% trong 1 năm dù đang làm công việc văn phòng.',
    content:
      `Bài viết đưa ra lộ trình cụ thể theo từng quý để nâng cấp kỹ năng, thương lượng lương, và mở rộng nguồn thu nhập thụ động dành cho dân văn phòng.`,
    author: 'PlanAI Team',
    date: '2024-02-01',
    readTime: '9 phút đọc',
    category: 'Nghề nghiệp',
    featured: false,
  },
  {
    id: 'tu-0-dong-den-so-huu-nha',
    title: 'Từ 0 Đồng Tiết Kiệm Đến Sở Hữu Căn Nhà Mơ Ước: Kế Hoạch 5 Năm',
    excerpt:
      'Lộ trình thực tế và kỷ luật tài chính để sở hữu căn nhà đầu tiên dù bắt đầu từ con số 0.',
    content:
      `Hướng dẫn chi tiết cách thiết lập mục tiêu, tiết kiệm, đầu tư và tối ưu chi phí để tích lũy đủ tiền mua nhà trong 5 năm.`,
    author: 'Ngọc Anh',
    date: '2024-02-10',
    readTime: '11 phút đọc',
    category: 'Mục tiêu lớn',
    featured: true,
  },
  // 14+ additional posts (placeholders, will be expanded to 1500+ từ theo yêu cầu)
  {
    id: 'ke-hoach-chi-tieu-50-30-20',
    title: 'Áp Dụng Quy Tắc 50/30/20 Để Quản Lý Chi Tiêu Thông Minh',
    excerpt: 'Cách vận dụng quy tắc 50/30/20 cho người đi làm bận rộn.',
    content:
      'Giới thiệu quy tắc 50/30/20, ví dụ thực tế theo mức lương 8-20 triệu, mẹo tối ưu từng nhóm chi tiêu và theo dõi bằng PlanAI.',
    author: 'PlanAI Team',
    date: '2024-03-01',
    readTime: '7 phút đọc',
    category: 'Quản lý chi tiêu',
  },
  {
    id: 'phat-trien-ky-nang-de-tang-luong',
    title: '5 Kỹ Năng Giúp Bạn Tăng Lương Nhanh Trong Môi Trường Văn Phòng',
    excerpt: 'Tập trung kỹ năng tạo ra giá trị cao và dễ đo lường.',
    content:
      'Roadmap học kỹ năng và cách chứng minh hiệu quả công việc để thăng tiến nhanh.',
    author: 'Minh Quân',
    date: '2024-03-05',
    readTime: '8 phút đọc',
    category: 'Nghề nghiệp',
  },
  {
    id: 'thu-nhap-thu-dong-cho-nguoi-ban-ron',
    title: '7 Nguồn Thu Nhập Thụ Động Phù Hợp Cho Người Bận Rộn',
    excerpt: 'Các mô hình nhẹ nhàng, vốn thấp, dễ triển khai song song công việc chính.',
    content:
      'So sánh ưu nhược điểm và rủi ro của 7 nguồn thu nhập thụ động phổ biến.',
    author: 'Lan Phương',
    date: '2024-03-10',
    readTime: '9 phút đọc',
    category: 'Kiếm tiền online',
  },
  {
    id: 'phan-tich-thi-truong-crypto-cho-nguoi-moi',
    title: 'Phân Tích Thị Trường Crypto Cho Người Mới: Rủi Ro Và Cơ Hội',
    excerpt: 'Góc nhìn cân bằng, tránh FOMO, xây chiến lược an toàn.',
    content:
      'Nguyên tắc quản trị rủi ro, phân bổ vốn, và khung đánh giá dự án.',
    author: 'PlanAI Research',
    date: '2024-03-15',
    readTime: '10 phút đọc',
    category: 'Thị trường',
  },
  {
    id: 'ke-hoach-tra-no-thong-minh',
    title: 'Kế Hoạch Trả Nợ Thông Minh: Avalanche vs. Snowball',
    excerpt: 'Chọn chiến lược phù hợp để trả nợ nhanh nhất với chi phí thấp.',
    content: 'So sánh 2 phương pháp, ví dụ con số và checklist thực thi.',
    author: 'PlanAI Team',
    date: '2024-03-20',
    readTime: '8 phút đọc',
    category: 'Quản lý nợ',
  },
  {
    id: 'xay-dung-quy-du-phong-3-6-thang',
    title: 'Xây Dựng Quỹ Dự Phòng 3-6 Tháng: Bắt Đầu Từ Đâu?',
    excerpt: 'Chiến thuật tiết kiệm nhanh và gửi ở đâu để tối ưu.',
    content: 'Các bước thực tế xây quỹ khẩn cấp và thói quen duy trì.',
    author: 'Thu Hằng',
    date: '2024-03-25',
    readTime: '7 phút đọc',
    category: 'Tiết kiệm',
  },
  {
    id: 'ren-luyen-thoi-quen-tai-chinh',
    title: 'Rèn Luyện 10 Thói Quen Tài Chính Giúp Bạn Giàu Lên Mỗi Ngày',
    excerpt: 'Những thói quen nhỏ tạo ra sự khác biệt lớn trong 1-3 năm.',
    content: 'Bảng theo dõi thói quen và cách tự thưởng để bám kỷ luật.',
    author: 'PlanAI Team',
    date: '2024-04-01',
    readTime: '9 phút đọc',
    category: 'Tư duy tài chính',
  },
  {
    id: 'ke-hoach-luong-thuong-van-phong',
    title: 'Kế Hoạch Tăng Lương Và Thưởng Dành Cho Nhân Sự Văn Phòng',
    excerpt: 'OKR cá nhân, kỹ thuật đàm phán, và hồ sơ thành tích.',
    content: 'Template báo cáo thành tích và script thương lượng lương.',
    author: 'HR Insider',
    date: '2024-04-05',
    readTime: '10 phút đọc',
    category: 'Nghề nghiệp',
  },
  {
    id: 'hoc-gi-de-tang-thu-nhap',
    title: 'Học Gì Để Tăng Thu Nhập 2-3 Lần?',
    excerpt: 'Lộ trình học kỹ năng số: AI, dữ liệu, marketing, no-code.',
    content: 'Khung 90-180 ngày để chuyển nghề/thăng tiến bằng kỹ năng số.',
    author: 'PlanAI Academy',
    date: '2024-04-10',
    readTime: '11 phút đọc',
    category: 'Học tập & kỹ năng',
  },
  {
    id: 'ke-hoach-mua-xe-3-nam',
    title: 'Kế Hoạch Mua Xe Trong 3 Năm: Tích Lũy Và Tối Ưu Chi Phí',
    excerpt: 'Lựa chọn tài chính thông minh để sở hữu xe hơi đầu tiên.',
    content: 'Dự toán chi phí sở hữu xe và chiến lược tài chính phù hợp.',
    author: 'PlanAI Team',
    date: '2024-04-15',
    readTime: '8 phút đọc',
    category: 'Mục tiêu lớn',
  },
  {
    id: 'nen-dau-tu-vao-ban-than',
    title: 'Đầu Tư Vào Bản Thân: Tỷ Suất Lợi Nhuận Cao Nhất',
    excerpt: 'Tại sao học tập và kỹ năng mang lại lợi nhuận cao hơn gửi tiết kiệm?',
    content: 'Case study tăng thu nhập nhờ học kỹ năng và áp dụng vào công việc.',
    author: 'PlanAI Academy',
    date: '2024-04-20',
    readTime: '9 phút đọc',
    category: 'Học tập & kỹ năng',
  },
  {
    id: 'xay-dung-portfolio-cho-nguoi-bat-dau',
    title: 'Xây Dựng Danh Mục Đầu Tư Dành Cho Người Bắt Đầu',
    excerpt: 'Nguyên tắc phân bổ tài sản theo tuổi và khẩu vị rủi ro.',
    content: 'Ví dụ phân bổ 60/40, DCA, và tái cân bằng định kỳ.',
    author: 'PlanAI Research',
    date: '2024-04-25',
    readTime: '10 phút đọc',
    category: 'Đầu tư',
  },
  {
    id: 'tu-duy-tai-chinh-1-3-5-nam',
    title: 'Tư Duy Tài Chính Theo Mốc 1-3-5 Năm: Kế Hoạch Rõ, Đích Đến Nhanh',
    excerpt: 'Phương pháp lập kế hoạch theo mốc thời gian để tránh lạc hướng.',
    content: 'Cách đặt mục tiêu, phân rã công việc và đo tiến độ.',
    author: 'PlanAI Team',
    date: '2024-05-01',
    readTime: '8 phút đọc',
    category: 'Tư duy tài chính',
  },
  {
    id: 'toi-uu-chi-phi-song-tai-tphcm',
    title: 'Tối Ưu Chi Phí Sống Tại TP.HCM/Hà Nội Mà Vẫn Giữ Chất Lượng',
    excerpt: 'Chiến thuật tiết kiệm tiền nhà, đi lại, ăn uống thông minh.',
    content: 'Bảng so sánh chi phí và mẹo tối ưu theo từng quận.',
    author: 'Local Guide',
    date: '2024-05-05',
    readTime: '9 phút đọc',
    category: 'Quản lý chi tiêu',
  },
  {
    id: 'phong-ngua-rui-ro-tai-chinh',
    title: 'Phòng Ngừa Rủi Ro Tài Chính Cá Nhân: Bảo Hiểm Và Dự Phòng',
    excerpt: 'Tối ưu chi phí bảo hiểm mà vẫn an tâm.',
    content: 'Các loại bảo hiểm nên có theo độ tuổi và gia cảnh.',
    author: 'PlanAI Team',
    date: '2024-05-10',
    readTime: '8 phút đọc',
    category: 'Quản trị rủi ro',
  },
  {
    id: 'chi-den-dau-tu-do',
    title: 'Chi Đều Rồi Đầu Tư Đều: Công Thức Bền Vững Cho Người Bận Rộn',
    excerpt: 'Thiết lập hệ thống tự động để không bỏ lỡ việc đầu tư.',
    content: 'Thiết lập auto-transfer, DCA và checklist hàng tháng.',
    author: 'Ngọc Minh',
    date: '2024-05-15',
    readTime: '7 phút đọc',
    category: 'Tiết kiệm',
  },
  {
    id: 'ke-hoach-hoc-ngoai-ngu-de-nang-thu-nhap',
    title: 'Kế Hoạch Học Ngoại Ngữ Để Nâng Thu Nhập Trong 6-12 Tháng',
    excerpt: 'Lộ trình học áp dụng ngay cho công việc: tiếng Anh, tiếng Trung.',
    content: 'Mục tiêu, tài nguyên học và cách đo ROI của kỹ năng ngôn ngữ.',
    author: 'PlanAI Academy',
    date: '2024-05-20',
    readTime: '10 phút đọc',
    category: 'Học tập & kỹ năng',
  },
  {
    id: 'ke-hoach-nghi-huu-som-fire',
    title: 'Kế Hoạch Nghỉ Hưu Sớm (FIRE): Bắt Đầu Từ Thu Nhập 10-20 Triệu',
    excerpt: 'Áp dụng nguyên tắc FIRE thực tế với mức lương phổ biến tại Việt Nam.',
    content: 'Tỷ lệ tiết kiệm, đầu tư và lộ trình để đạt độc lập tài chính.',
    author: 'PlanAI Research',
    date: '2024-05-25',
    readTime: '12 phút đọc',
    category: 'Tự do tài chính',
  },
  {
    id: 'phan-tich-thi-truong-lao-dong',
    title: 'Phân Tích Thị Trường Lao Động: Ngành Nào Đang Trả Lương Cao?',
    excerpt: 'Dữ liệu mức lương và nhu cầu tuyển dụng theo thành phố lớn.',
    content: 'Gợi ý chuyển ngành và kỹ năng nên học để tăng thu nhập.',
    author: 'PlanAI Data',
    date: '2024-06-01',
    readTime: '11 phút đọc',
    category: 'Thị trường',
  },
  {
    id: 'mua-nha-hay-thue-nha',
    title: 'Nên Mua Nhà Hay Thuê Nhà? Phân Tích Dành Cho Người Đi Làm',
    excerpt: 'So sánh toàn diện chi phí, cơ hội, và rủi ro.',
    content: 'Bảng tính điểm ra quyết định theo tình huống cá nhân.',
    author: 'PlanAI Team',
    date: '2024-06-05',
    readTime: '10 phút đọc',
    category: 'Mục tiêu lớn',
  },
  // Added posts to reach 25 total (placeholders; content can be expanded with markdown files)
  {
    id: 'ngan-sach-cho-nguoi-moi-di-lam',
    title: 'Ngân Sách Thông Minh Cho Người Mới Đi Làm',
    excerpt: 'Cách phân bổ thu nhập tháng đầu tiên để không bị cháy túi.',
    content: 'Khung 50/30/20 linh hoạt, mẹo cắt giảm chi tiêu và theo dõi dòng tiền.',
    author: 'PlanAI Team',
    date: '2024-06-10',
    readTime: '8 phút đọc',
    category: 'Quản lý chi tiêu',
  },
  {
    id: 'kien-tao-thu-nhap-phu',
    title: 'Kiến Tạo Thu Nhập Phụ: Từ Ý Tưởng Đến 10 Triệu/Tháng',
    excerpt: 'Lộ trình 90 ngày để xây nguồn thu nhập phụ bền vững.',
    content: 'Chọn ngách, sản phẩm hóa kỹ năng và tối ưu kênh bán.',
    author: 'PlanAI Academy',
    date: '2024-06-15',
    readTime: '10 phút đọc',
    category: 'Kiếm tiền online',
  },
  {
    id: 'khung-nang-cap-nghe-nghiep',
    title: 'Khung Nâng Cấp Nghề Nghiệp: Từ Junior Lên Senior',
    excerpt: 'Xây dựng hồ sơ thành tích và kỹ năng tạo giá trị cốt lõi.',
    content: 'OKR cá nhân, case study và chiến lược thăng tiến.',
    author: 'HR Insider',
    date: '2024-06-20',
    readTime: '9 phút đọc',
    category: 'Nghề nghiệp',
  },
  {
    id: 'chien-luoc-dau-tu-theo-muc-tieu',
    title: 'Chiến Lược Đầu Tư Theo Mục Tiêu: Ngắn, Trung Và Dài Hạn',
    excerpt: 'Phân bổ tài sản theo thời gian đạt mục tiêu.',
    content: 'Khung đầu tư 1-3-5 năm và tái cân bằng danh mục.',
    author: 'PlanAI Research',
    date: '2024-06-25',
    readTime: '11 phút đọc',
    category: 'Đầu tư',
  },
  {
    id: 'tai-chinh-cap-do-gia-dinh-tre',
    title: 'Tài Chính Cấp Độ Gia Đình Trẻ: Kế Hoạch Chi, Tiết Kiệm Và Đầu Tư',
    excerpt: 'Thiết kế ngân sách hai người, quỹ khẩn cấp và bảo hiểm.',
    content: 'Checklist tài chính sau kết hôn và nguyên tắc quản trị rủi ro.',
    author: 'PlanAI Team',
    date: '2024-06-30',
    readTime: '12 phút đọc',
    category: 'Tài chính cá nhân',
  },
]
